const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConnections: () => ipcRenderer.invoke('get-connections'),
  saveConnection: (alias, url) => ipcRenderer.invoke('save-connection', alias, url),
  deleteConnection: (alias) => ipcRenderer.invoke('delete-connection', alias),
  connect: (url1, url2) => ipcRenderer.invoke('connect', url1, url2),
  connectSingle: (url) => ipcRenderer.invoke('connect-single', url),
  disconnect: () => ipcRenderer.invoke('disconnect'),
  listDatabases: (side) => ipcRenderer.invoke('list-databases', side),
  compareDatabases: () => ipcRenderer.invoke('compare-databases'),
  listCollections: (side, dbName) => ipcRenderer.invoke('list-collections', side, dbName),
  compareCollections: (sourceDbName, targetDbName) => ipcRenderer.invoke('compare-collections', sourceDbName, targetDbName),
  compareDocuments: (sourceDbName, targetDbName, collName, options) => ipcRenderer.invoke('compare-documents', sourceDbName, targetDbName, collName, options),
  getDocument: (side, dbName, collName, docId) => ipcRenderer.invoke('get-document', side, dbName, collName, docId),
  insertDocument: (side, dbName, collName, doc) => ipcRenderer.invoke('insert-document', side, dbName, collName, doc),
  updateDocument: (side, dbName, collName, docId, doc) => ipcRenderer.invoke('update-document', side, dbName, collName, docId, doc),
  deleteDocument: (side, dbName, collName, docId) => ipcRenderer.invoke('delete-document', side, dbName, collName, docId),
  patchDocument: (side, dbName, collName, docId, doc) => ipcRenderer.invoke('patch-document', side, dbName, collName, docId, doc),
  copyDocument: (fromSide, toSide, dbName, collName, docId) => ipcRenderer.invoke('copy-document', fromSide, toSide, dbName, collName, docId),
  copyCollection: (fromSide, toSide, dbName, collName) => ipcRenderer.invoke('copy-collection', fromSide, toSide, dbName, collName),
  copyCollectionAcross: (fromSide, fromDb, fromColl, toSide, toDb, toColl) => ipcRenderer.invoke('copy-collection-across', fromSide, fromDb, fromColl, toSide, toDb, toColl),
  createDatabase: (side, dbName, collName) => ipcRenderer.invoke('create-database', side, dbName, collName),
  dropCollection: (side, dbName, collName) => ipcRenderer.invoke('drop-collection', side, dbName, collName),
  dropDatabase: (side, dbName) => ipcRenderer.invoke('drop-database', side, dbName),
  createCollection: (side, dbName, collName, options) => ipcRenderer.invoke('create-collection', side, dbName, collName, options),
  renameField: (side, dbName, collName, oldName, newName) => ipcRenderer.invoke('rename-field', side, dbName, collName, oldName, newName),
  deleteDocuments: (side, dbName, collName, query) => ipcRenderer.invoke('delete-documents', side, dbName, collName, query),
  executeQuery: (side, dbName, collName, options) => ipcRenderer.invoke('execute-query', side, dbName, collName, options),
  importConnections: () => ipcRenderer.invoke('import-connections'),
});
